mims-harvard/TDC

README.md

Fix https://github.com/mims-harvard/TDC/issues/2

Update README with conda installation instructions

---

tdc/chem_utils.py

Tianfan dev

---

tdc/chem_utils.py

mol convert details completion

mol convert: details

---

tdc/benchmark.py
tdc/metadata.py
tdc/utils.py

There are two splits:
- one is by metric (css, loewe, zip, bliss, hsa)
- the other is by tissue type (cell lines can be grouped into 9 tissues
Also added code to the base benchmark class for dealing with pickle files instead of csv

Drugsyn benchmark group

---

examples/single_pred/drugcombo/README.md
examples/single_pred/drugcombo/featurize_drugs.py
examples/single_pred/drugcombo/model_classes.py
examples/single_pred/drugcombo/train_MLP.py
tdc/metadata.py

Simple MLP regression model for training a baseline for the drugcombo benchmark group

Drugcombo benchmark model

---

tdc/metadata.py
tdc/single_pred/tox.py

Fixes #124: category-task-dataset hierarchy now completely defined in `tdc.metadata`

---

tdc/multi_pred/multi_pred_dataset.py

Editing to suggest a way to solve issue raised in https://github.com/mims-harvard/TDC/issues/136.

Support multi-instances split using cold_split method

---

tdc/generation/sbdd.py
tdc/utils/load.py

1. update biopandas installation warning, processing message, warning for long time processing
2. save atomic number instead of one-hot encoding
3. add protein remove Hs and ligand remove Hs as two different options
4. fix error about mismatch between protein atom coordinate and atom type
5. update google doc accordingly
6. move failure reporting to the end

fix small issues in SBDD dataset support

---

tdc/metadata.py
tdc/multi_pred/__init__.py
tdc/multi_pred/trialoutcome.py

Local test (loading data and pytest) is successful. we need to wait for the publish of Harvard dataverse.

clinical trial outcome prediction dataset

---

.circleci/config.yml

Fixed
https://app.circleci.com/pipelines/github/mims-harvard/TDC/614/workflows/9dd4eb51-98e1-4c41-8b5a-6fbd552584ba/jobs/619

rdkit change caused failed circle-ci build

---

environment.yml
tdc/resource/cellxgene_census.py
tdc/test/dev_tests/utils_tests/test_misc_utils.py
tdc/test/test_resources.py
tdc/utils/label.py

also -- fix issue introduced to label.py when migrating to python 3.9
tdc/utils/label.py

fix up remaining test issues

---

tdc/dataset_configs/config.py
tdc/dataset_configs/config_map.py
tdc/dataset_configs/pinnacle_dti.py
tdc/feature_generators/base.py
tdc/feature_generators/data_feature_generator.py
tdc/feature_generators/resource.py
tdc/metadata.py
tdc/multi_pred/perturboutcome.py
tdc/multi_pred/single_cell.py
tdc/resource/dataloader.py
tdc/test/test_dataloaders.py
tdc/utils/load.py

This will serve as the benchmark dataset for the new single-cell DTI task.
cc @michellemli

Add PINNACLE DTI data and dataloader to TDC

---

tdc/benchmark_group/scdti_group.py
tdc/test/test_benchmark.py

Add single-cell DTI benchmark (Neurips benchmarks)

---

tdc/benchmark_group/counterfactual_group.py
tdc/multi_pred/perturboutcome.py
tdc/test/test_benchmark.py

using random split
todo: cell-line-based and perturbation-unseen splits

complete counterfactual benchmark

---

tdc/benchmark_group/geneperturb_group.py
tdc/multi_pred/anndata_dataset.py
tdc/multi_pred/perturboutcome.py
tdc/test/test_benchmark.py

closes https://github.com/mims-harvard/TDC/pull/268

Bug fixes perturb

---

news/index.html

add news and features of tdc-2

Update index.html -- tdc-2 on newsfeed

---

environment.yml
requirements.txt
tdc/single_pred/mpc.py

https://github.com/mims-harvard/TDC/issues/296
fyi @shenwanxiang @marinkaz

New MPC task and MoleculeACE datasets

---

tdc/single_pred/mpc.py
tdc/test/test_dataloaders.py

package deployed and demo in 205 of GH readme demos

finish mpc dataloader

---

tdc/test/test_model_server.py

also pick from more generalized layer (penultimate)

Geneformer server -- extract cell type specific gene embeddings

---

.github/workflows/pre-commit.yml

asked in https://github.com/mims-harvard/TDC/pull/360#issuecomment-2764701886
personally, I would just enable the bot for this repo, https://github.com/marketplace/pre-commit-ci

ci: adding pre-commit check
